name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3307:3306

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

      # JavaScriptのセットアップとESLintの実行
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "19.9.0"

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn eslint
